services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile
      - ./website:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - webnet

  tor:
    image: dockurr/tor
    container_name: tor
    restart: always
    volumes:
      - ./configs/torrc:/etc/tor/torrc
      - ./hidden_service:/var/lib/tor/hidden_service
    networks:
      - webnet

networks:
  webnet:

volumes:
  caddy_data:
  caddy_config:
  caddy_logs: